apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synology-csi
resources:
  - namespace.yaml
# TODO: later add
  - secret-client-info.yaml
  - storageclass-synology-iscsi.yaml
  - csi-controller.yaml
  - csi-node.yaml
  - csi-driver.yaml
