apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - minio-buckets-job.yaml
  - minio-service.yaml
  - minio-statefulset.yaml
  - namespace.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - service.yaml
