apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kan
resources:
  - ../../base/kan
  - ingress.yaml
  - minio-ingress.yaml
  - kan-secret.sops.yaml
  - kan-s3-secret.sops.yaml
  - minio-root-secret.sops.yaml
  - tasks-storage-tls-secret.sops.yaml
  - tasks-tls-secret.sops.yaml
